### ISSUE TITLE
update to v0.14

### ISSUE THREAD

**Issue by sergiodxa** [markfinger/react-render#2]
Are you going to update to react v0.14 and use react-dom?

**Comment by markfinger** [comment]
There's no reason not to, although it'd be good to maintain backwards compatibility.

Probably need to interrogate the version number in `react/package.json` and then jump through some hoops

**Comment by markfinger** [comment]
Actually, I think bumping the version would be enough to cover backwards compatibility. If you find the time, do you mind opening a PR with the `react-dom` support?

**Comment by rpastorelle** [comment]
This can be closed ;)
